version: '3'
services:
  son-mongo:
    image: mongo
    container_name: son-mongo
    ports:
        - 27017:27017
    restart: always
  tng-analytics-engine:
    build:
     context: .
     dockerfile: Dockerfile
    container_name:  tng-analytics-engine 
    ports:
      - "8085:8085"
    depends_on:
      - son-mongo
      - tng-analytics-rserver
    restart: always
  tng-analytics-rserver:
    build:
     context: .
     dockerfile: tng-analytics-rserver/Dockerfile
    container_name: tng-analytics-rserver
    ports:
      - "8083:80"
    restart: always
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/prometheus.yml
    volumes:
    - ./prometheus.yml:/prometheus.yml:ro
    depends_on:
    - cadvisor
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - tng-analytics-rserver
    - tng-analytics-engine
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: always
    expose:
      - 9091
    ports:
      - "9091:9091"
    
